// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using borderCounterApi.Helpers;

#nullable disable

namespace borderCounterApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("borderCounterApi.Models.BorderInformationInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Border")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<int>>("CarLanes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("PrevMinutes")
                        .HasColumnType("integer");

                    b.Property<List<int>>("SpeedLanes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalCars")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BorderInformationIntervals");
                });
#pragma warning restore 612, 618
        }
    }
}
